name: dashboard-opiop

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard_web
    ports:
      - "18000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
